# This is a basic workflow to help you get started with Actions

name: Android Pull Request CI

on:
  pull_request:
    branches: 
      - 'main'
    types:
      - opened

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: set up Android SDK
        uses: android-actions/setup-android@v3
        
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Clean the project
        run: ./gradlew clean
        
      - name: Test the project
        run: ./gradlew test --no-build-cache

  verify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v4

      - name: set up JDK 17
        uses: actions/setup-java@v3
        with:
          distribution: 'corretto'
          java-version: '17'

      - name: set up Android SDK
        uses: android-actions/setup-android@v3

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        
      - name: Clean the project
        run: ./gradlew clean

      - name: Run detekt
        run: ./gradlew detekt --no-build-cache
